---
env:
  browser: true
  es6: true
  node: true
  jest: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:prettier/recommended
rules:
  prettier/prettier: error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/prefer-regexp-exec': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unsafe-assignment': warn
  '@typescript-eslint/no-unsafe-member-access': warn
  '@typescript-eslint/no-floating-promises': warn