---
env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - react
rules:
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/explicit-function-return-type': off
  prettier/prettier: error
