---
env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
  - react-app
plugins:
  - prettier
  - react
rules:
  prettier/prettier: error
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
