---
allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: false
extension:
  - ts
forbid-only: false
forbid-pending: false
full-trace: false
growl: false
inline-diffs: false
recursive: false
reporter: spec
retries: 1
slow: 75
sort: false
spec: test/**/*.spec.ts
timeout: false
trace-warnings: true
ui: bdd
