---
env:
  browser: true
  es6: true
  node: true
  jest: true
  mocha: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - react-app
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - react
  - react-hooks
rules:
  prettier/prettier: error
  '@typescript-eslint/prefer-regexp-exec': off
