---
env:
  browser: true
  es6: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - react-hooks
  - prettier
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
rules:
  prettier/prettier: error
